// src/App.tsx
import { createSignal, For, Show, Switch, Match } from 'solid-js';
import type { Component } from 'solid-js';

const workingHoursPerYear = 1950;
const workingDaysPerYear = 230;
const workingDaysPerMonth = 22;
const shitsPerDay = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

const App: Component = () => {
  const [income, setIncome] = createSignal(600000);
  const [shitsTakenPerDay, setShitsTakenPerDay] = createSignal(1);
  const [timeItTakesToShit, setTimeItTakesToShit] = createSignal(0);
  const hourlySalary = () => income() / workingHoursPerYear;
  const dailyShittingTime = () => shitsTakenPerDay() * (timeItTakesToShit() / 60);
  const dailyShitIncome = () => dailyShittingTime() * hourlySalary();
  const monthlyShitIncome = () => dailyShitIncome() * workingDaysPerMonth;
  const yearlyShitIncome = () => dailyShitIncome() * workingDaysPerYear;
  const showResults = () => timeItTakesToShit() > 0 && !Number.isNaN(timeItTakesToShit());

  return (
    <main class="svg-bg flex w-full">
      <div class="center w-full">
        <h1 class="pt-6 font-medium text-2xl text-gray-100">Shitcalc.com</h1>
        <p class="text-gray-100 mt-4">After much demand, it's finally here!</p>
        <form class="mt-6">
          <p class="text-gray-100">Yearly Salary</p>
          <label>
            <input
              class="w-64"
              type="range"
              min="600000"
              max="1500000"
              step="25000"
              value={income()}
              onInput={(e) => setIncome(Number(e.currentTarget.value))}
            />
            <p class="text-gray-100">{income()}</p>
          </label>
          <p class="mt-8 text-gray-100">Shits per day</p>
          <select
            class="w-64 h-8 rounded-lg bg-gray-100"
            value={shitsTakenPerDay()}
            onInput={(e) => setShitsTakenPerDay(Number(e.currentTarget.value))}
          >
            <For each={shitsPerDay}>
              {(count) => <option value={count}>{count}</option>}
            </For>
          </select>

          <p class="mt-8 text-gray-100">Length of visit (minutes)</p>
          <label>
            <input
              class="w-64"
              type="range"
              min="5"
              max="30"
              step="5"
              value={timeItTakesToShit()}
              onInput={(e) => setTimeItTakesToShit(Number(e.currentTarget.value))}
            />
            <p class="text-gray-100">{timeItTakesToShit()}</p>
          </label>
          <Show when={Number.isNaN(timeItTakesToShit())}>
            <p class="text-red-300 text-2xl">Please enter a number</p>
          </Show>
        </form>
        <Switch>
          <Match when={shitsTakenPerDay() > 3}>
            <div class="mt-6 animate-pulse">
              <p class="text-red-500 text-3xl font-bold">
                Seek out a medical professional 🚑
              </p>
              <p class="text-gray-300 mt-2">
                That is {shitsTakenPerDay()} times a day. You are dying.
              </p>
            </div>
          </Match>
          <Match when={showResults()}>
            <div class="mt-6">
              <p class="text-gray-100 text-xl">
                Daily Shit Income {Math.round(dailyShitIncome())}kr
              </p>
              <p class="text-gray-100 text-xl">
                Monthly Shit Income {Math.round(monthlyShitIncome())}kr
              </p>
              <p class="text-gray-100 text-xl">
                Yearly Shit Income {Math.round(yearlyShitIncome())}kr
              </p>
            </div>
          </Match>
        </Switch>
        <div class="text-gray-100 absolute bottom-0 mb-4 ml-4">
          <a href="https://helge.dev">by helge.dev</a>
        </div>
      </div>
    </main>
  );
};

export default App;

// src/App.svelte
<script>
  const workingHoursPerYear = 1950;
  const workingDaysPerYear = 230;
  const workingDaysPerMonth = 22;
  let hourlySalary = 0;
  let dailyShittingTime = 0;
  let income = 500000;
  let shitsPerDay = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  let shitsTakenPerDay;
  let timeItTakesToShit = 0;
  let dailyShitIncome = 0;
  let monthlyShitIncome = 0;
  let yearlyShitIncome = 0;
  let calculationComplete = false;

  function calculateMoneyMadeWhileShitting() {
    if (isNaN(timeItTakesToShit)) {
      return;
    } else {
      hourlySalary = income / workingHoursPerYear;
      dailyShittingTime = shitsTakenPerDay * (timeItTakesToShit / 60);
      dailyShitIncome = dailyShittingTime * hourlySalary;
      monthlyShitIncome = dailyShitIncome * workingDaysPerMonth;
      yearlyShitIncome = dailyShitIncome * workingDaysPerYear;
      calculationComplete = true;
    }
  }
</script>

<svelte:head>
  <title>Shitcalc - Calculating shitty passive income.</title>
</svelte:head>

<main class="svg-bg flex w-full">
  <div class="center w-full">
    <h1 class="pt-6 font-medium text-2xl text-gray-100">Shitcalc.com</h1>
    <p class="text-gray-100 mt-4">After much demand, it's finally here!</p>
    <form class="mt-6">
      <p class="text-gray-100">Yearly Salary</p>
      <label>
        <input
          class="w-64"
          type="range"
          bind:value={income}
          on:change={calculateMoneyMadeWhileShitting}
          min="500000"
          max="1250000"
          step="25000"
        />
        <p class="text-gray-100">{income}</p>
      </label>
      <p class="mt-8 text-gray-100">Shits per day</p>
      <select
        selected
        class="w-64 h-8 rounded-lg"
        bind:value={shitsTakenPerDay}
        on:change={calculateMoneyMadeWhileShitting}
      >
        {#each shitsPerDay as shits}
          <option value={shits}>
            {shits}
          </option>
        {/each}
      </select>
      <p class="mt-8 text-gray-100">Length of visit (minutes)</p>
      <label>
        <input
          class="w-64"
          type="range"
          bind:value={timeItTakesToShit}
          on:change={calculateMoneyMadeWhileShitting}
          min="5"
          max="30"
          step="5"
        />
        <p class="text-gray-100">{timeItTakesToShit}</p>
      </label>
      {#if isNaN(timeItTakesToShit)}
        <p class="text-red-300 text-2xl">Please enter a number</p>
      {/if}
    </form>

    {#if !isNaN(timeItTakesToShit)}
      {#if calculationComplete}
        <p class="text-gray-100 text-xl mt-6">
          Daily Shit Income {Math.round(dailyShitIncome)}kr
        </p>
        <p class="text-gray-100 text-xl">
          Monthly Shit Income {Math.round(monthlyShitIncome)}kr
        </p>
        <p class="text-gray-100 text-xl">
          Yearly Shit Income {Math.round(yearlyShitIncome)}kr
        </p>
      {/if}
    {/if}
    <div class="text-gray-100 absolute bottom-0 mb-4 ml-4">
      <a href="https://helge.dev">by helge.dev</a>
    </div>
  </div>
</main>

<style lang="postcss" global>
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
  :root {
    font-family:
      -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans',
      'Helvetica Neue', sans-serif;
  }
  body {
    background-color: #330000;
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%25' height='100%25' viewBox='0 0 800 400'%3E%3Cdefs%3E%3CradialGradient id='a' cx='396' cy='281' r='514' gradientUnits='userSpaceOnUse'%3E%3Cstop offset='0' stop-color='%23D18'/%3E%3Cstop offset='1' stop-color='%23330000'/%3E%3C/radialGradient%3E%3ClinearGradient id='b' gradientUnits='userSpaceOnUse' x1='400' y1='148' x2='400' y2='333'%3E%3Cstop offset='0' stop-color='%23FA3' stop-opacity='0'/%3E%3Cstop offset='1' stop-color='%23FA3' stop-opacity='0.5'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill='url(%23a)' width='800' height='400'/%3E%3Cg fill-opacity='0.4'%3E%3Ccircle fill='url(%23b)' cx='267.5' cy='61' r='300'/%3E%3Ccircle fill='url(%23b)' cx='532.5' cy='61' r='300'/%3E%3Ccircle fill='url(%23b)' cx='400' cy='30' r='300'/%3E%3C/g%3E%3C/svg%3E");
    background-attachment: fixed;
    background-size: cover;
    height: 100vh;
    max-height: 100vh;
  }
  .center {
    margin: auto;
    text-align: center;
    margin-top: 20px;
  }
</style>
